### ISSUE TITLE
Add DFS

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#1]
In the graph theory directory, add the Depth First Search Algorithm.

**Comment by Ace117MC** [comment]
Can you assign this to me

**Comment by ayu16** [comment]
please can you assign this to me

**Comment by Manas502** [comment]
I would like to contribute

**Comment by ekdnam** [comment]
Sure! We don't assign here! Just make a PR!

**Comment by boom786** [comment]
I'll make a PR in c++.

**Comment by ekdnam** [comment]
@boom786 sure!

**Comment by ekdnam** [comment]
DFS added. Closing this issue now
