### ISSUE TITLE
Add documentation for A Star

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#10]
A Star is a graph traversal algorithm. Do enhance the repo by adding information about A Star!

The changes should be in `/Graph Theory/A Star/README.md`

**Comment by avnishsingh516** [comment]
#61 Added the explanation and algorithm of A star

**Comment by avnishsingh516** [comment]
i made the changes. please review the new committed code in #61

**Comment by ekdnam** [comment]
https://github.com/ekdnam/Algorithms/pull/61 solves the issue. Closing the issue now. Thanks!
