### ISSUE TITLE
Add documentation for Dijkstra Algorithm

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#11]
Dijkstra's Algorithm is used for finding the path between two nodes in a graph. Do enhance the repo by adding documentation for it!

The changes should be in `/Graph Theory/Dijkstra Algorithm/README.md`

**Comment by ayushi2805** [comment]
Hi @ekdnam, 
I would like to take this issue.

**Comment by Abhicoder03** [comment]
Hey , I would like work on it. Could you assign this to me.

**Comment by ekdnam** [comment]
We are not assigning anyone here right now! Go ahead and make a PR!

**Comment by Abhicoder03** [comment]
Sure @ekdnam

**Comment by ekdnam** [comment]
Docs have been added. Closing this issue now
