### ISSUE TITLE
Add Fibonacci Search (C++)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#12]
Add the C++ version of Fibonacci Search!

The code should be in `/Searching/Fibonacci Search`

Best of luck for your Open Source Journey!

**Comment by MathurAditya724** [comment]
Hey, I would like to  work on this. Can you assign this to me? 😄

**Comment by ekdnam** [comment]
We are not assigning anyone here right now! Go ahead and make a PR!

**Comment by ananya0504** [comment]
I can't fine this repository anywhere? Who owns it?

**Comment by ananya0504** [comment]
Hi, I recently put the required code, do check!

**Comment by ekdnam** [comment]
As this is solved, closing the issue
