### ISSUE TITLE
Add documentation for Fibonacci Search

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#14]
Fibonacci search is an algorithm which is used to efficiently search an array of objects.

Add the documentation for the algorithm.

It should be in `/Searching/Fibonacci Search/README.md`

Happy Open-Sourcing!

For your reference: [Wikipedia](https://en.wikipedia.org/wiki/Fibonacci_search_technique)

**Comment by Nivya-21** [comment]
Hey, I would like to contribute.

**Comment by ekdnam** [comment]
Yes sure! Go ahead and make a PR!

**Comment by ekdnam** [comment]
Docs have been added. Closing this issue now
