### ISSUE TITLE
Add Linear Search (C++)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#16]
Linear search is an algorithm which is used to search in an array of objects.

Add the code for it. It should be in `Searching/Linear Search`

Happy Open-Sourcing!

For your reference: [Wikipedia](https://en.wikipedia.org/wiki/Linear_search#Basic_algorithm)

**Comment by aansh-01** [comment]
hey can I do this task

**Comment by aansh-01** [comment]
Please assign this issue to me

**Comment by ekdnam** [comment]
Yes sure! Go ahead and make a PR!

**Comment by ekdnam** [comment]
We are not assigning anyone here right now, make the changes and submit a PR!

**Comment by Mayankjha997** [comment]
hey please assign me i want add algorithm in c.

**Comment by ekdnam** [comment]
Thanks @aansh-01 for your contribution! I am closing this issue now. Would be adding C, Java, Python issues as well!
