### ISSUE TITLE
Add documentation for Linear Search

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#18]
Linear search is an algorithm which is used to efficiently search an array of objects.

Add the documentation for the algorithm.

It should be in `/Searching/Linear Search/README.md`

Happy Open-Sourcing!

For your reference: [Wikipedia](https://en.wikipedia.org/wiki/Linear_search#Basic_algorithm)

**Comment by amitShindeGit** [comment]
Hey ekdnam,could you please assign this to me.I am willing to do this.

**Comment by akshitkumar450** [comment]
i would like to do it..please assign this to me.

**Comment by ekdnam** [comment]
We are not assigning anyone here right now! Go ahead make a PR!

**Comment by NidhiNivedita6** [comment]
Please assign this to me.

**Comment by amitShindeGit** [comment]
Okay.

**Comment by Mayankjha997** [comment]
Please assign this to me. I will do this

**Comment by ekdnam** [comment]
We are not assigning anyone here right now! Go ahead make a PR!

**Comment by ekdnam** [comment]
As it has been solved, closing the issue

**Comment by akshitkumar450** [comment]
thank you for merging my PR
