### ISSUE TITLE
Add Bucket Sort (C++)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#19]
Bucket sort is an algorithm that works by distributing array elements in what are known as buckets!

Add the C++ version of Bucket Sort!

The code should be in `/Sorting/Bucket Sort`

Happy Open-Sourcing!

For your referene: [Bucket Sort](https://en.wikipedia.org/wiki/Bucket_sort)

**Comment by sudiptog81** [comment]
Working on this!

**Comment by ekdnam** [comment]
This issue will be closed now
