### ISSUE TITLE
Add BFS

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#2]
In the graph theory directory, add a BFS graph traversal algorithm.

**Comment by ayu16** [comment]
can you assign this to me

**Comment by coding-sourabh** [comment]
assign this to me i will , contribute in cpp

**Comment by anishjain94** [comment]
Added BSF in Graph, Updated Folder Structure, Deleted EXE files PR - #7

**Comment by ekdnam** [comment]
Sure! Just make a PR! We are not assigning anyone here, the issues are up for grabs

**Comment by anishjain94** [comment]
Made BFS Input Dynamic - PR - #7
