### ISSUE TITLE
Add documentation for Bucket Sort

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#20]
Bucket sort is an algorithm that works by distributing array elements in what are known as buckets!

The docs should be in `/Sorting/Bucket Sort/README.md`

Happy Open-Sourcing!

For your reference: (Wikipedia)[https://en.wikipedia.org/wiki/Bucket_sort]

**Comment by Dutta-SD** [comment]
Hi @ekdnam 
I am new to open source and I would like to work on this. What I wanted to ask was whether I need to give the code as well as the documentation update. 
Thank you

**Comment by ekdnam** [comment]
Hey @Dutta-SD ! 

If you want to add both, go right ahead! While making the PR, mention both the issues. That would be it!

**Comment by Dutta-SD** [comment]
Hey
I have made the pull request. Do check it out

**Comment by Dutta-SD** [comment]
Changed the code to accept user input @ekdnam
