### ISSUE TITLE
Bellman Ford Algorithm | Graph | C++

### ISSUE THREAD

**Issue by ivinaypathak** [ekdnam/Algorithms#26]
### Bellman Ford Algorithm

- Used to find the shortest path to all other vertex from the source.

- It works for both positive and negative weight edges.

- Time Complexity: O(VE)

I would like to add this to your repo.

**Comment by ekdnam** [comment]
Yes sure! I will create a subdirectory for the same.

**Comment by ekdnam** [comment]
Make the changes in `Graph Theory/Bellman Fold Algorithm`

**Comment by itsarjun12** [comment]
i have done this please look at that.

**Comment by ekdnam** [comment]
Bellman Ford has been added, closing this issue now
