### ISSUE TITLE
Add A Star (Python)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#32]
A Star is a graph traversal algorithm. Do enhance the repo by the python version of A Star!

**The working branch should be python**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/python)

The changes should be in `/Graph Theory/A Star`

**The file should be named AStar.py**

Happy Open-Sourcing!

**Comment by subhakr11droy** [comment]
Hi @ekdnam, I am taking up this issue :)

**Comment by subhakr11droy** [comment]
Hi @ekdnam,

Added a pr for this issue. #119 
Please look into it :) 

Thanks,
Shubhakar
