### ISSUE TITLE
Add Bellman Ford (Python)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#35]
Bellman Ford is a graph traversal algorithm. Do enhance the repo by the python version of Bellman Ford!

**The working branch should be python**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/python)

The changes should be in `/Graph Theory/Bellman Ford`

**The file should be named BellmanFord.py**

Happy Open-Sourcing!

**Comment by Uyadav207** [comment]
@ekdnam please assign this to me

**Comment by gunishjain** [comment]
Can I do this?

**Comment by ekdnam** [comment]
Sure. We are not assigning here right now. Go ahead and make a PR!
