### ISSUE TITLE
Add DFS (Python)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#36]
Depth First Search is a graph traversal algorithm. Do enhance the repo by the python version of DFS!

**The working branch should be python**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/python)

The changes should be in `/Graph Theory/DFS`

**The file should be named DFS.py**

Happy Open-Sourcing!

**Comment by avnishsingh516** [comment]
#68 68 created PR for the DFS in python . 
please ... check this out

**Comment by avnishsingh516** [comment]
i made the changes. Please, review the new commit in #68

**Comment by ekdnam** [comment]
DFS has been added. Closing this issue now
