### ISSUE TITLE
Add Dijkstra Algorithm (Python)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#38]
Dijkstra is a graph traversal algorithm. Do enhance the repo by the python version of Dijkstra!

**The working branch should be python**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/python)

The changes should be in `/Graph Theory/Dijkstra`

**The file should be named Dijkstra.py**

Happy Open-Sourcing!

**Comment by avnishsingh516** [comment]
#65 created a PR for Dijkstra in Python with explanation

**Comment by ekdnam** [comment]
Dijkstra has been added. Closing this issue now
