### ISSUE TITLE
Add Binary Search (Python)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#39]
Binary Search is an algorithm used to quickly search an array of objects. Do enhance the repo by the python version of Binary Search!

**The working branch should be python**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/python)

The changes should be in `/Searching/Binary Search`

**The file should be named BinarySearch.py**

Happy Open-Sourcing!

**Comment by raniphore** [comment]
Please assign to me

**Comment by jaskarans2000** [comment]
can I work on it?

**Comment by gennady9** [comment]
I Implemented and created a pull request:
https://github.com/ekdnam/Algorithms/pull/66

**Comment by jatinjain001** [comment]
I want to work with it .. Can you please assign it to me
