### ISSUE TITLE
Add bubble sort (python)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#41]
Bubble sort is an algorithm used to efficiently arrange the different objects of an array in a specific order.

**The working branch should be python**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/python)

The changes should be in `/Sorting/Insertion Sort`

**The file should be named InsertionSort.py**

Happy Open-Sourcing!

**Comment by ankurjain00** [comment]
Hi @ekdnam I would like to work on the issue

**Comment by rykulkarni** [comment]
Let me know if its still open and can be assigned.

**Comment by ankurjain00** [comment]
@ekdnam The tag needs to be Hacktoberfest with capital H instead of hacktoberfest for the pull request to count can you please update the tag

**Comment by ekdnam** [comment]
Okay done.

**Comment by ekdnam** [comment]
As this issue has been solved, closing it. Thank you all for your contributions!
