### ISSUE TITLE
Add Bubble Sort (C)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#42]
Bubble sort is an algorithm used to efficiently arrange the different objects of an array in a specific order.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Sorting/Insertion Sort`

**The file should be named bubbleSort.c**

Happy Open-Sourcing!

**Comment by aman-kumar-jh** [comment]
I am up for this task 👍. Please assign me

**Comment by ekdnam** [comment]
Sure! Go ahead and make a PR! Make sure that the branch is C

**Comment by ekdnam** [comment]
We are not assigning anyone right now

**Comment by ananya0504** [comment]
please check
