### ISSUE TITLE
Add insertion sort (c)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#43]
Insertion sort is an algorithm used to efficiently arrange the different objects of an array in a specific order.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Sorting/Insertion Sort`

**The file should be named insertionSort.c**

Happy Open-Sourcing!

**Comment by ankan10** [comment]
I would like to contribute, Kindly please assign to me.
Regards,
Ankan

**Comment by Procoder16** [comment]
Hi @ekdnam, I would like to contribute to this.

Please assign me this.

I would love to do this.

**Comment by ananya0504** [comment]
please check

**Comment by Procoder16** [comment]
@ekdnam I have added the Insertion Sort program in C language.

#111 

Kindly review it and let me know if any change is required.

**Comment by jatinjain001** [comment]
@ekdnam  I want to work on this please asssign it to me

**Comment by PritiShaw** [comment]
@ekdnam I have made the PR #121 
Please review it.
