### ISSUE TITLE
Add merge sort (c)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#44]
Merge sort is an algorithm used to efficiently arrange the different objects of an array in a specific order.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Sorting/Merge Sort`

**The file should be named mergeSort.c**

Happy Open-Sourcing!

**Comment by Uyadav207** [comment]
@ekdnam , please assign this task to me.

**Comment by avnishsingh516** [comment]
#58 please.... check this PR . I made this PR for merge sort in C

**Comment by Uyadav207** [comment]
@ekdnam , please mention that how you are assigning task.

Because, many people just pulling request, without being assigned.. are these open issues ?

**Comment by avnishsingh516** [comment]
i made the changes. Please review the changes in #58

**Comment by ekdnam** [comment]
@uyadav all are open issues, we are not assigning anyone right now

**Comment by ananya0504** [comment]
please check

**Comment by ekdnam** [comment]
Merge sort has been added. Closing this issue now
