### ISSUE TITLE
Add quicksort (c)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#45]
Quicksort is an algorithm used to efficiently arrange the different objects of an array in a specific order.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Sorting/Quicksort`

**The file should be named quicksort.c**

Happy Open-Sourcing!

**Comment by ACAA06** [comment]
I would like to contribute to it. Please assign this to me.

**Comment by ACAA06** [comment]
#51 here is the pull request for quick sort in c

**Comment by ananya0504** [comment]
Please check

**Comment by ke3peR007** [comment]
can I work on it like to do version of python

**Comment by ekdnam** [comment]
Merge sort has been added. Closing this issue now.
