### ISSUE TITLE
Add selection sort (c)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#46]
Selection sort is an algorithm used to efficiently arrange the different objects of an array in a specific order.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Sorting/Selection Sort`

**The file should be named selectionSort.c**

Happy Open-Sourcing!

**Comment by akankshast** [comment]
I would be happy to contribute to this issue. Kindly assign it to me.
Regards,
Akanksha

**Comment by Procoder16** [comment]
@ekdnam Sir, I would like to contribute to this.

Please assign this to me.

**Comment by PritiShaw** [comment]
@ekdnam, I have made the PR, [#79 ](https://github.com/ekdnam/Algorithms/pull/79) here is the pull request for selection sort in c.

**Comment by ananya0504** [comment]
please check

**Comment by ekdnam** [comment]
Selection sort has been added. Closing this issue now
