### ISSUE TITLE
Add binary search (c)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#47]
Binary Search is an algorithm used to efficiently find an element in array of objects.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Searching/Binary Search`

**The file should be named binarySearch.c**

Happy Open-Sourcing!

**Comment by rane-shubham** [comment]
I would like to contribute. Please assign this to me.

**Comment by jatinjain001** [comment]
I would like to contribute 
please assign it to me

**Comment by Procoder16** [comment]
Hi @ekdnam Sir, I would like to contribute to this.

Would love to do it.

Please assign this to me.

**Comment by saiharsha-22** [comment]
@ekdnam can you please assign this task to me I would like to code the problem using Java programming language. And I will add inorder, pre-order and post order traversal also using binary search.

**Comment by ekdnam** [comment]
You can create an issue for this! I'll add my thoughts their. Great addition!

**Comment by ekdnam** [comment]
This issue has been solved. I am closing it
