### ISSUE TITLE
Add Fibonacci Search (c)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#48]
Fibonacci Search is an algorithm used to efficiently find an element in array of objects.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Searching/Fibonacci Search`

**The file should be named fibonacciSearch.c**

Happy Open-Sourcing!

**Comment by jain13tushar** [comment]
Hi @ekdnam 

I can work on this if you can assign it to me

Regards,
@Tushar

**Comment by avnishsingh516** [comment]
#56 please... check this PR i made the PR for fibonacci serach in C

**Comment by avnishsingh516** [comment]
i made the changes.. Please, review the new committed code in #56

**Comment by ekdnam** [comment]
https://github.com/ekdnam/Algorithms/pull/56 solves the issue. Would be closing this now. Thanks everyone for their contributions!
