### ISSUE TITLE
Add linear search (c)

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#49]
Linear Search is an algorithm used to efficiently find an element in array of objects.

**The working branch should be c**

The branch can be found [here](https://github.com/ekdnam/Algorithms/tree/c)

The changes should be in `/Searching/Linear Search`

**The file should be named linearSearch.c**

Happy Open-Sourcing!

**Comment by sagunjaiswal** [comment]
assign me this would love addding it

**Comment by ACAA06** [comment]
#51 please do check this PR for linear search in c

**Comment by avnishsingh516** [comment]
#53 please.... check this out
I made a PR for linear search

**Comment by jatinjain001** [comment]
if it is open then please assign it to me

**Comment by ekdnam** [comment]
As it has been resolved, closing the issue
