### ISSUE TITLE
Add A star

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#8]
Add the C++ version of A Star algorithm for Graph Traversal.

The code should be in `/Graph Theory/A Star`

For further reference: [Wikipedia](https://en.wikipedia.org/wiki/A*_search_algorithm)

**Comment by sakshi-negi123** [comment]
please assign this to me

**Comment by ekdnam** [comment]
We are not assigning here right now! Go ahead and submit a PR with your changes!

**Comment by ekdnam** [comment]
A Star C++ has been added. Closing this issue now
