### ISSUE TITLE
Add Dijkstra Algorithm

### ISSUE THREAD

**Issue by ekdnam** [ekdnam/Algorithms#9]
Add the C++ version of Dijkstra Algorithm.

The code should be in `/Graph Theory/Dijkstra Algorithm`

For further reference: [Brilliant](https://brilliant.org/wiki/dijkstras-short-path-finder/)

**Comment by SudaravanM** [comment]
Hey, @ekdnam I would like to work on it.

**Comment by gunjan543** [comment]
I would like to contribute to this issue in c++ language

**Comment by verma-pulkit** [comment]
I would like to contribute. Provide me the chance

**Comment by saundaryasinha19** [comment]
hey @ekdnam i would like to work on this

**Comment by ekdnam** [comment]
Dijkstra C++ has been added. Closing this issue now
